### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by kpx-dev** [willprice/generator-ansible#2]
readline.js:924
            throw err;
            ^

Error: Cannot find module '../lib/BaseAnsibleGenerator'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kien/Dropbox/8341app/deploy/node_modules/generator-ansible-2/app/index.js:2:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by medialwerk** [comment]
+1

**Comment by willprice** [comment]
Hello both, sorry for some reason I've only just seen both of these issues, I haven't been getting notifications for this repo. I'll have a look shortly and fix. My apologies!

**Comment by floodedcodeboy** [comment]
I have a similar issue... installed it then tried to run it: 

```
>yo ansible-2
module.js:341
    throw err;
    ^

Error: Cannot find module '../lib/BaseAnsibleGenerator'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jacob/workspace/deployment-bits/node_modules/generator-ansible-2/app/index.js:2:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by willprice** [comment]
Sorry I left this for so long guys. I think I've fixed it, if not reply and I'll make a concerted effort to fix this! Thank you for your patience.
